import HTML-Template-Pro 0.53 from CPAN
git-cpan-module:   HTML-Template-Pro
git-cpan-version:  0.53
git-cpan-authorid: VIY
git-cpan-file:     authors/id/V/VI/VIY/HTML-Template-Pro-0.53.tar.gz

diff --git a/Makefile.PL b/Makefile.PL
--- a/Makefile.PL
+++ b/Makefile.PL
@@ -2,8 +2,8 @@ use 5.005;
 use ExtUtils::MakeMaker;
 $Verbose = 1;
 
-$O_FILES=qw/procore.o pstack.o pbuffer.o proscope.o expr.o pstring.o tmpllog.o/;
-#  loadfile.o calc.o exprtool.o
+$O_FILES=qw/procore.o pbuffer.o proscope.o expr.o pstring.o tmpllog.o/;
+#  loadfile.o calc.o exprtool.o pstack.o
 
 my $INC='-I.';
 my $DEFINE='';
@@ -11,7 +11,10 @@ my $LIBS='-lm';
 
 my $PCRE=1;
 my $DEBUG=0;
-$PCRE=0 if $^O =~ /win/i;
+my $MMAP=1;
+#$PCRE=0 if $^O =~ /win/i;
+$PCRE=has_pcre();
+
 
 my $i;
 for ($i=0; $i<@ARGV; $i++)  {
@@ -19,6 +22,8 @@ for ($i=0; $i<@ARGV; $i++)  {
 	$PCRE=$1;
     } elsif ($ARGV[$i]=~/DEBUG=(.+)/) {
 	$DEBUG=$1;
+    } elsif ($ARGV[$i]=~/MMAP=(.+)/) {
+	$MMAP=$1;
     } else {
 	next;
     }
@@ -65,17 +70,113 @@ WriteMakefile(
 sub MY::postamble {
     return <<'MAKE_FRAG';
 expr.c: calc.inc exprtool.inc
-procore.o: loadfile.inc
+procore\$(OBJ_EXT): loadfile.inc pstack.inc
 
 rpm: dist
 	rpmbuild -ta --clean --target i586-alt-linux HTML-Template-Pro-$(VERSION).tar.gz
 
 index.html: README Makefile
-	echo '<html><body><p><a href="http://sourceforge.net"><img src="http://sourceforge.net/sflogo.php?group_id=138507&amp;type=5" width="210" height="62" border="0" alt="SourceForge.net Logo" /></a><br> <a href="http://sourceforge.net/projects/html-tmpl-pro/">SourceForge Summary page of the project</a><br><a href="http://www.imath.kiev.ua/~vlasenko/">Home page of the author</a><br><a href="http://prdownloads.sourceforge.net/html-tmpl-pro/HTML-Template-Pro-${VERSION}.tar.gz?download">Download</a><p><pre>' > $@
+	echo '<html><body><p><a href="http://sourceforge.net"><img src="http://sourceforge.net/sflogo.php?group_id=138507&amp;type=5" width="210" height="62" border="0" alt="SourceForge.net Logo" /></a><br> <a href="http://sourceforge.net/projects/html-tmpl-pro/">SourceForge Summary page of the project</a><br><a href="http://www.imath.kiev.ua/~vlasenko/">Home page of the author</a><br><a href="http://prdownloads.sourceforge.net/html-tmpl-pro/HTML-Template-Pro-$(VERSION).tar.gz?download">Download</a><p><pre>' > $@
 	cat $< >> $@
 	echo '</pre></body></html>' >> $@
 
 
 MAKE_FRAG
+}
+
+# those tests are copied from Time-HiRes-01.20
+
+sub TMPDIR {
+    my $TMPDIR =
+	(grep(defined $_ && -d $_ && -w _,
+	      ((defined $ENV{'TMPDIR'} ? $ENV{'TMPDIR'} : undef),
+	       qw(/var/tmp /usr/tmp /tmp))))[0]
+		   unless defined $TMPDIR;
+    $TMPDIR || die "Cannot find writable temporary directory.\n";
+}
+
+sub try_compile_and_link {
+    my ($c, $cccmd, $ccflags) = @_;
+
+    my ($ok) = 0;
+    my ($tmp) = ($^O eq 'VMS') ? "tmp$$" : TMPDIR . '/' . "tmp$$";
+    local(*TMPC);
+
+    my $obj_ext = $Config{obj_ext} || ".o";
+    unlink("$tmp.c", "$tmp$obj_ext");
+
+    if (open(TMPC, ">$tmp.c")) {
+	print TMPC $c;
+	close(TMPC);
+	my $COREincdir = $Config{'archlibexp'} . '/' . 'CORE';
+	$ccflags .= ' '. $Config{'ccflags'} . ' ' . "-I$COREincdir";
+	my $cc=$Config{'cc'};
+	$cc||='cc';
+	if ($^O eq 'VMS') {
+            my $perl_core = $Config{'installarchlib'};
+            $perl_core =~ s/\]$/.CORE]/;
+            $cccmd = "$cc /include=(perl_root:[000000],$perl_core) $tmp.c"; 
+        }
+	$cccmd = "$cc -o $tmp $ccflags $tmp.c @$LIBS"
+	 unless (defined $cccmd);
+    print "trying $cccmd\n";
+	system($cccmd);
+	if ($^O eq 'VMS') {
+	    $ok = -s "$tmp$obj_ext" && -x _;
+	    unlink("$tmp.c", "$tmp$obj_ext");
+        }
+        else
+        {
+	    $ok = -s $tmp && -x _;
+	    unlink("$tmp.c", $tmp);
+        }
+    }
+    
+    $ok;
+}
+
+sub has_pcre {
+    print "looking for pcre...\n";
+    return 1 if try_compile_and_link('
+#include <pcre.h>
+    static int foo()
+    {
+	return 0;
+    }
+    int main (int argc, char** argv)
+    {
+	foo();
+    }
+',undef, '-I/usr/include/pcre -lpcre');
+    return 0;
+}
+
+sub has_x {
+    my ($x) = @_; 
+
+    return 1 if
+    try_compile_and_link(<<EOM);
+#include "EXTERN.h"
+#include "perl.h"
+#include "XSUB.h"
+
+#ifdef I_UNISTD
+#   include <unistd.h>
+#endif
+
+#ifdef I_SYS_TYPES
+#   include <sys/types.h>
+#endif
+
+#ifdef I_SYS_TIME
+#   include <sys/time.h>
+#endif
+
+int main _((int argc, char** argv, char** env))
+{
+	$x;
+}
+EOM
+    return 0;
 }
 
